---
# === Configuration Kubernetes ===
k8s_version: "1.28.5"
k8s_packages:
  - kubelet
  - kubeadm
  - kubectl
k8s_repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/ /"
k8s_gpg_key: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/Release.key"

# === Runtime Containerd (recommandé) ===
containerd_config: |
  version = 2
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "registry.k8s.io/pause:3.9"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
        runtime_type = "io.containerd.runc.v2"
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true

# === Configuration Réseau ===
pod_network_cidr: "10.244.0.0/16"
flannel_manifest: "https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"

# === Optimisation Système ===
sysctl_params:
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1
  vm.swappiness: 0
