#cloud-config
system_info:
  default_user:
    name: ""

runcmd:
  # Crée l'utilisateur si inexistant
  - id -u nudger-k8s >/dev/null 2>&1 || useradd -m -s /bin/bash -G sudo nudger-k8s
  - echo "nudger-k8s ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nudger-k8s

  # Configure SSH pour ton accès
  - mkdir -p /home/nudger-k8s/.ssh
  - echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIqKTlRSzPT86KSpW6rBpSqUbRrtCvi48K/L+FzaBjzc loicgourmelon@gmail.com' > /home/nudger-k8s/.ssh/authorized_keys
  - chown -R nudger-k8s:nudger-k8s /home/nudger-k8s/.ssh
  - chmod 700 /home/nudger-k8s/.ssh
  - chmod 600 /home/nudger-k8s/.ssh/authorized_keys

  # Installe les paquets utiles
  - apt-get update && apt-get install -y git curl vim openssh-client

  # Clone le repo en HTTPS (pas besoin de clé privée)
  - sudo -u nudger-k8s git clone https://github.com/loicgo29/nudger.git /home/nudger-k8s/nudger

