#cloud-config
# yamllint disable rule:comments
#cloud-config

users:
  - name: ${USER}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ID_SSH_PUB}

packages:
  - git
  - curl
  - vim
  - openssh-client
runcmd:
  # Installe les paquets utiles
  - apt-get update && apt-get install -y git curl vim openssh-client
