#cloud-config
# yamllint disable rule:comments
#cloud-config

users:
  - name: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIqKTlRSzPT86KSpW6rBpSqUbRrtCvi48K/L+FzaBjzc loicgourmelon@gmail.com

packages:
  - git
  - curl
  - vim
  - openssh-client
runcmd:
  # Installe les paquets utiles
  - apt-get update && apt-get install -y git curl vim openssh-client
