apiVersion: v1
kind: Service
metadata:
  name: xwiki
  namespace: nudger-xwiki
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: xwiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xwiki
  namespace: nudger-xwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xwiki
  template:
    metadata:
      labels:
        app: xwiki
    spec:
      containers:
        - name: xwiki
          image: xwiki:lts-mysql-tomcat
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              value: xwiki
            - name: DB_PASSWORD
              value: xwikipass
            - name: DB_HOST
              value: xwiki-mysql
            - name: DB_DATABASE
              value: xwiki
