---
- name: Ensure root has a password
  ansible.builtin.user:
    name: root
    password: "$6$KqWnS3H9$8trHwCqW1jv1PldjUZyPrjHk7Lk4pxq65j.FHfojQo6FJ94L0W3nE6m9oQ7bM8Xun3zQO2U7KpVqpL7h9c9aC/"

- name: Ensure users exist with pre-hashed passwords
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | join(',') }}"
    shell: /bin/bash
    create_home: yes
    password: "{{ item.password }}"   # déjà un hash
  loop: "{{ users_k8s }}"

- name: Add SSH public key for each user
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_public_key }}"
    state: present
  loop: "{{ users_k8s }}"
  when: item.ssh_public_key is defined

- name: Ensure .kube directory exists
  file:
    path: "/home/{{ item.name }}/.kube"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0700'
  loop: "{{ users_k8s }}"

- name: Copy kubeconfig for each user
  copy:
    src: "{{ item.kubeconfig }}"
    dest: "/home/{{ item.name }}/.kube/config"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
    remote_src: yes
  loop: "{{ users_k8s }}"
  when: item.kubeconfig is defined and item.kubeconfig != ""

- name: Ensure .bash_aliases exists
  file:
    path: "/home/{{ item.name }}/{{ bash_aliases_file }}"
    state: touch
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
  loop: "{{ users_k8s }}"

- name: Deploy common aliases for Kubernetes
  copy:
    src: "bash_aliases"
    dest: "/home/{{ item.name }}/{{ bash_aliases_file }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0644'
  loop: "{{ users_k8s }}"

- name: Source .bash_aliases in .bashrc
  lineinfile:
    path: "/home/{{ item.name }}/.bashrc"
    regexp: '^source ~/.bash_aliases'
    line: 'source ~/.bash_aliases'
    state: present
  loop: "{{ users_k8s }}"

- name: Install kubectx and kubens
  git:
    repo: https://github.com/ahmetb/kubectx.git
    dest: "/opt/kubectx"
    version: master
    force: yes
  when: install_kubectx or install_kubens
  become: yes

- name: Symlink kubectx binary
  file:
    src: /opt/kubectx/kubectx
    dest: /usr/local/bin/kubectx
    state: link
  when: install_kubectx
  become: yes

- name: Symlink kubens binary
  file:
    src: /opt/kubectx/kubens
    dest: /usr/local/bin/kubens
    state: link
  when: install_kubens
  become: yes

- name: Ensure Bash completion directories exist
  file:
    path: "/home/dev-loic/.local/share/bash-completion/completions"
    state: directory
    owner: dev-loic
    group: dev-loic
    mode: '0700'

- name: Generate kubectl completion for dev-loic
  shell: "kubectl completion bash > /home/dev-loic/.local/share/bash-completion/completions/kubectl"
  args:
    creates: "/home/dev-loic/.local/share/bash-completion/completions/kubectl"
  become: yes
  become_user: dev-loic

- name: Add kg function and kubectl completion to .bashrc
  blockinfile:
    path: "/home/dev-loic/.bashrc"
    block: |
      # -----------------------------
      # Kubectl alias/function and completion
      # -----------------------------
      unalias kg 2>/dev/null || true
      kg() {
          kubectl "$@"
      }
      if [ -f ~/.local/share/bash-completion/completions/kubectl ]; then
          source ~/.local/share/bash-completion/completions/kubectl
      fi
      complete -F __start_kubectl kg
  become: yes
  become_user: dev-loic

- name: Ensure correct permissions for .bashrc
  file:
    path: "/home/dev-loic/.bashrc"
    owner: dev-loic
    group: dev-loic
    mode: '0644'

- name: Configure global Git user name and email for dev-loic
  ansible.builtin.git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { key: "user.name", value: "LoGo" }
    - { key: "user.email", value: "logo@gmail.com" }
  loop_control:
    loop_var: item
  become: yes
  become_user: dev-loic

- name: Copy deploy key for Git access
  ansible.builtin.copy:
    src: "~/.ssh/id_ed25519"
    dest: "/home/{{ item.name }}/.ssh/id_ed25519"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
  loop: "{{ users_k8s }}"

- name: Clone Git repositories for each user
  ansible.builtin.git:
    repo: "git@github.com:loicgo29/nudger.git"
    dest: "/home/{{ item.name }}/nudger"
    key_file: "/home/{{ item.name }}/.ssh/id_ed25519"
    accept_hostkey: yes
    version: main
  loop: "{{ users_k8s }}"
  become: yes
  become_user: "{{ item.name }}"

- name: Add dev-loic to sudo group
  user:
    name: dev-loic
    groups: sudo
    append: yes

