---
repos:
  # Hooks génériques utiles
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: [--unsafe] # autorise les anchors/aliases YAML avancés
      - id: mixed-line-ending
        args: [--fix=lf]

  # Formatage Python si tu as du code Python (facultatif)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Lint YAML (plus strict que check-yaml)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$
        args: ["-c", ".yamllint"]

  # Lint Ansible
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.7.0
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - "ansible>=9.0.0"
        args:
          - "-c"
          - ".ansible-lint"

  # (Optionnel) Détecter des secrets/clé privées qui fuitent
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: >
          (?x)(
            ^group_vars/vault\.yml$|
            ^roles/.*/files/.*\.vault$|
            ^roles/.*/files/id_.*   # tes clés privées vaultées
          )
