---
repos:
  # Hooks génériques utiles
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: [--unsafe]  # autorise les anchors/aliases YAML avancés
      - id: mixed-line-ending
        args: [--fix=lf]

  # Formatage Python (si besoin)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Lint YAML (plus strict que check-yaml)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$
        args: ["-c", ".yamllint"]
        exclude: ^k8s-apps/

  # Hook local pour installer les collections Galaxy nécessaires à Ansible
  - repo: local
    hooks:
      - id: galaxy-collections
        name: ansible-galaxy collection install
        language: system
        pass_filenames: false
        entry: >
          bash -lc '
            set -euo pipefail
            ansible-galaxy collection install
              -r infra/k8s_ansible/collections/requirements.yml
              -p infra/k8s_ansible/collections
          '

  # Lint Ansible
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.6.1
    hooks:
      - id: ansible-lint
        pass_filenames: false
        args: ["-p", "infra/k8s_ansible"]
        entry: bash -lc 'ANSIBLE_CONFIG=$PWD/ansible.cfg ansible-lint -p infra/k8s_ansible'
        additional_dependencies:
          - ansible==9.3.0
        language_version: python3

  # (Optionnel) Détection de secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          (?x)(
            ^group_vars/vault\.yml$|
            ^roles/.*/files/.*\.vault$|
            ^roles/.*/files/id_.*
          )

default_language_version:
  python: /Users/loicgourmelon/.pyenv/versions/3.11.9/bin/python3.11
