---
- name: Ensure git present
  apt: {name: git, state: present, update_cache: true}

- name: Prepare workdir
  file: {path: /root/gitops-work, state: directory, mode: '0755'}

- name: Clone nudger-gitops (HTTPS + PAT)
  when: gitops.use_github_pat
  git:
    repo: "https://{{ github.pat | urlencode }}@github.com/{{ gitops.github_owner }}/{{ gitops.github_repo }}.git"
    dest: /root/gitops-work/repo
    version: "{{ gitops.branch }}"
    force: true
    update: true
  no_log: true

- name: Clone nudger-gitops (SSH)
  when: gitops.use_deploy_key
  git:
    repo: "{{ github.repo_ssh_url }}"
    dest: /root/gitops-work/repo
    version: "{{ gitops.branch }}"
    force: true
    update: true
    key_file: /root/.ssh/gitops_deploy_key

- name: Drop update script
  copy:
    dest: /root/gitops-work/gitops_update.py
    mode: '0755'
    content: "{{ lookup('file', role_path + '/files/gitops_update.py') }}"

- name: Run update script (generate/normalize YAML)
  command: >
    python3 /root/gitops-work/gitops_update.py
    --repo /root/gitops-work/repo
    --service-type {{ gitops_update.service_type }}
    --node-port {{ gitops_update.node_port | default('', true) }}
    --ingress-host {{ gitops_update.ingress_host }}
    --include-ingress-nginx {{ 'true' if gitops_update.include_ingress_nginx else 'false' }}
  register: update_out
  changed_when: update_out.stdout is search('CHANGED: true')

- name: Configure git identity
  when: update_out.stdout is search('CHANGED: true')
  shell: |
    cd /root/gitops-work/repo
    git config user.name  "gitops-bot"
    git config user.email "gitops-bot@local"

- name: Commit changes
  when: update_out.stdout is search('CHANGED: true')
  shell: |
    set -e
    cd /root/gitops-work/repo
    git add -A
    git commit -m "chore(gitops): normalize clusters/lab and whoami manifests"

- name: Push changes
  when: update_out.stdout is search('CHANGED: true')
  shell: |
    cd /root/gitops-work/repo
    git push origin {{ gitops.branch }}

- name: Reconcile after push
  shell: |
    set -e
    flux -n flux-system reconcile kustomization cluster-lab --with-source --timeout=5m
  environment: {KUBECONFIG: /root/.kube/config}
