{{- $fullName := include "xwiki.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "xwiki.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{ toYaml .Values.commonAnnotations | indent 4 }}
    {{- end }}
type: Opaque
data:
  mysql-root-password: {{ .Values.externalDB.rootPassword | b64enc | quote }}
  mysql-user: {{ .Values.externalDB.user | b64enc | quote }}
  mysql-password: {{ .Values.externalDB.password | b64enc | quote }}
  mysql-database: {{ .Values.externalDB.database | b64enc | quote }}

{{- range $file, $values := .Values.customConfigsSecrets }}
  {{- range $key, $value := $values }}
    {{- if not (index $value "secret") }}
      {{- regexReplaceAll "\\W+" $key "_" | nindent 2 }}: {{ $value.value | b64enc | quote }}
    {{- else if and (not $value.name) (not $value.key) }}
      {{- regexReplaceAll "\\W+" $key "_" | nindent 2 }}: {{ $value.value | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}

{{- range $key, $value := .Values.javaOptsSecrets }}
  {{- if not (index $value "secret") }}
    {{- regexReplaceAll "\\W+" $key "_" | nindent 2 }}: {{ $value.value | b64enc | quote }}
  {{- else if and (not $value.name) (not $value.key) }}
    {{- regexReplaceAll "\\W+" $key "_" | nindent 2 }}: {{ $value.value | b64enc | quote }}
  {{- end }}
{{- end }}
