apiVersion: v1
kind: PersistentVolume
metadata:
  name: xwiki-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/xwiki
  persistentVolumeReclaimPolicy: Retain
