apiVersion: v1
kind: Service
metadata:
  name: xwiki
  namespace: open4goods
spec:
  type: NodePort  # LoadBalancer si cloud
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080   # facultatif
  selector:
    app: xwiki

