---
# playbooks/site.yml
# Playbook principal pour provisionner une VM DevOps + Kubernetes
- name: Bootstrap DevOps
  import_playbook: 01-bootstrap-devops.yml
- name: 02-infra_containerd.yml
  import_playbook: 02-infra_containerd.yml
- name: 03-kubernetes.yml
  import_playbook: 03-kubernetes.yml
- name: 03-A-vault.yml
  import_playbook: 03-A-vault.yml
- name: 03-B-k8s-users.yml
  import_playbook: 03-B-k8s-users.yml
#- name: 03-C-clone_repo_git.yml
#  import_playbook: 03-C-clone_repo_git.yml
#- name: 04-gitops_scaffold.yml
#  import_playbook: 04-gitops_scaffold.yml
- name: 05-flux.yml
  import_playbook: 05-flux.yml
- name: 06-sync_apps.yml
  import_playbook: 06-sync_apps.yml
