Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false

  # Port SSH personnalisé
  config.vm.network :forwarded_port, guest: 22, host: 50226, id: "ssh", auto_correct: true
  config.vm.network :forwarded_port, guest: 30081, host: 8080, auto_correct: true

  # Configuration QEMU adaptée
  config.vm.provider "qemu" do |qe|
    qe.qemu_dir = "/usr/bin/"
    qe.arch = "x86_64"
    qe.memory = "8192"       # 3 Go RAM pour VM
    qe.smp = "4"             # 2 vCPU
    qe.cpu = "qemu64"
    qe.machine = "q35"
    qe.net_device = "virtio-net-pci"
    qe.disk_bus = "virtio"

    # Disque dynamique QCOW2
    qe.disksize = "80G"      # 80 Go, s'adapte si utilisation < 80 Go
  end
end

