Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # ✅ On empêche toute génération de clé SSH auto
  config.ssh.insert_key = false

  # ✅ On évite les ports par défaut du box
  config.vm.network :forwarded_port, guest: 22, host: 50222, id: "ssh", auto_correct: false

  config.vm.provider "qemu" do |qe|
    qe.qemu_dir = "/usr/bin/"
    qe.arch = "x86_64"
    qe.memory = "2048"
    qe.smp = "4"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.net_device = "virtio-net-pci"
  end
end

