Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folders.clear   # Désactive tout sync folder
  config.ssh.insert_key = false

  NODES = [
    { hostname: "kubm1", ip: "192.168.26.10", cpus: 2, mem: 2048 }
  ]

  NODES.each do |node|
    config.vm.define node[:hostname] do |vm|
      vm.vm.hostname = node[:hostname]
      vm.vm.synced_folder ".", "/vagrant", disabled: true, type: "none"

      vm.vm.provider "qemu" do |qemu|
        qemu.qemu_dir = "/usr/bin/"
        qemu.arch = "x86_64"
        qemu.memory = node[:mem]
        qemu.smp = node[:cpus]
        qemu.machine = "q35"
        qemu.cpu = "max"
        qemu.net_device = "virtio-net-pci"
      end

      vm.vm.provision "shell", inline: <<-SHELL
        sudo tee /etc/netplan/01-netcfg.yaml > /dev/null <<EOF
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - #{node[:ip]}/24
      gateway4: 192.168.26.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
EOF
        sudo netplan apply
      SHELL
    end
  end
end
