---
- name: Ensure base deps + python kubernetes
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - git
      - python3
      - python3-pip
      - python3-kubernetes
    update_cache: true
    state: present

# On COPIE le kubeconfig (pas de symlink => pas de boucle)
- name: Ensure /root/.kube exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Install kubeconfig for root (copy, no symlink)
  ansible.builtin.copy:
    src: "{{ kubeconfig }}"
    dest: /root/.kube/config
    owner: root
    group: root
    mode: '0600'
    remote_src: true

