---
- name: Download Helm {{ helm_version }}
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /tmp/helm.tgz
    mode: '0644'

- name: Install helm into /usr/local/bin
  ansible.builtin.unarchive:
    src: /tmp/helm.tgz
    dest: /usr/local/bin
    remote_src: true
    extra_opts: ['--strip-components=1','linux-amd64/helm']
  args:
    creates: "{{ helm_bin }}"

- name: Ensure helm is executable
  ansible.builtin.file:
    path: "{{ helm_bin }}"
    state: file
    mode: '0755'

