---
- name: Add Helm repo ingress-nginx
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "{{ ingress_repo }}"

- name: Add Helm repo jetstack
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "{{ cert_repo }}"

- name: helm repo update
  ansible.builtin.command: "{{ helm_bin }} repo update"
  changed_when: false

- name: Ensure namespaces exist
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
  loop:
    - "{{ ingress_ns }}"
    - "{{ cert_ns }}"
