---
- name: Assert helm_values_dir exists (controller)
  delegate_to: localhost
  become: false
  ansible.builtin.stat:
    path: "{{ helm_values_dir }}"
  register: hv
  run_once: true

- name: Fail if helm_values_dir missing
  delegate_to: localhost
  become: false
  ansible.builtin.assert:
    that:
      - hv.stat.exists
    fail_msg: "helm_values_dir introuvable: {{ helm_values_dir }}"
  run_once: true

