---
# 1) cert-manager (installer les CRDs)
# Chart >= v1.12 : crds.enabled=true (installCRDs est deprecated)
- name: Install/upgrade cert-manager (with CRDs)
  kubernetes.core.helm:
    name: "{{ cert_release }}"
    chart_ref: "{{ cert_chart }}"
    chart_version: "{{ cert_version }}"
    release_namespace: "{{ cert_ns }}"
    create_namespace: false
    atomic: true
    wait: true
    timeout: 600s
    values:
      crds:
        enabled: true
    values_files: "{{ cert_values_files | default([]) }}"

# 2) ingress-nginx
- name: Install/upgrade ingress-nginx
  kubernetes.core.helm:
    name: "{{ ingress_release }}"
    chart_ref: "{{ ingress_chart }}"
    chart_version: "{{ ingress_version }}"
    release_namespace: "{{ ingress_ns }}"
    create_namespace: false
    atomic: true
    wait: true
    timeout: 600s
    values_files: "{{ ingress_values_files | default([]) }}"

