---
# Fail-fast kubeconfig lisible
- name: Assert kubeconfig present
  ansible.builtin.stat:
    path: "{{ kubeconfig }}"
  register: kc

- name: Fail if kubeconfig missing/empty
  ansible.builtin.assert:
    that:
      - kc.stat.exists
      - (kc.stat.size | int) > 0
    fail_msg: "kubeconfig {{ kubeconfig }} introuvable/vide. Lance d'abord 'kubernetes-setup.yml'."

- import_tasks: 01_prep.yml
- import_tasks: 02_helm_cli.yml
- import_tasks: 03_repos.yml
- import_tasks: 04_values_path.yml
- import_tasks: 05_deploy.yml

