---
# Chemins
helm_bin: /usr/local/bin/helm
kubeconfig: /etc/kubernetes/admin.conf
# Versions (exemples stables au moment d'écriture)
helm_version: "3.15.4"
ingress_nginx:
  ns: ingress-nginx
  release: ingress-nginx
  chart: ingress-nginx
  repo_name: ingress-nginx
  repo_url: "https://kubernetes.github.io/ingress-nginx"
  chart_version: "4.11.3" # pin chart
  values: {} # tu peux injecter des valeurs ici
  # Exemple NodePort (décommente et adapte):
  # values:
  #   controller:
  #     service:
  #       type: NodePort
  #       nodePorts:
  #         http: 30080
  #         https: 30443
cert_manager:
  ns: cert-manager
  release: cert-manager
  chart: cert-manager
  repo_name: jetstack
  repo_url: "https://charts.jetstack.io"
  chart_version: "v1.15.1" # pin chart
  values:
    installCRDs: true # indispensable pour CRDs
