---
- name: Install required packages for Longhorn & tooling
  apt:
    name:
      - nfs-common
      - open-iscsi
      - jq
      - curl
      - socat
      - multipath-tools
    state: present
    update_cache: yes

- name: Disable multipathd service (conflicts with Longhorn)
  systemd:
    name: multipathd
    enabled: false
    state: stopped

- name: Ensure dm_crypt module is loaded now
  modprobe:
    name: dm_crypt
    state: present

- name: Persist dm_crypt module across reboots
  copy:
    dest: /etc/modules-load.d/dm_crypt.conf
    content: "dm_crypt\n"
    owner: root
    group: root
    mode: '0644'

- name: Configure sysctl for kube/longhorn
  copy:
    dest: /etc/sysctl.d/99-kubernetes.conf
    content: |
      net.ipv4.ip_forward = 1
      fs.inotify.max_user_instances = 8192
      fs.inotify.max_user_watches  = 1048576
  notify: Reload sysctl

- name: Ensure swap is off (runtime)
  command: swapoff -a
  when: ansible_swaptotal_mb|default(0) | int > 0

- name: Ensure swap is disabled (fstab)
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#]\S+)\s+\S+\s+swap\s+\S+'
    replace: '# \1 swap disabled for Kubernetes'
  register: swap_fstab
  changed_when: swap_fstab.msg is defined
