---
- name: Include common variables
  include_vars: "{{ role_path }}/../common/vars/main.yml"
  tags: always

- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker GPG key (ASCII)
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: /tmp/docker-archive-keyring.asc
    mode: '0644'
  become: yes

- name: Convert GPG key to binary format
  command: "gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker-archive-keyring.asc"
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Remove temporary ASCII GPG key
  file:
    path: /tmp/docker-archive-keyring.asc
    state: absent
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker
    update_cache: yes
  become: yes

- name: Install apt dependencies
  apt:
    name: "{{ ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg'] + common_dependencies }}"
    state: present
    cache_valid_time: 36000
  become: yes

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: yes

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
  retries: 3
  delay: 5
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

