---
- name: Include common variables
  include_vars: "{{ role_path }}/../common/vars/main.yml"
  tags: always

- name: Install common dependencies
  apt:
    name: "{{ common_dependencies }}"
    state: present
    update_cache: yes
  become: yes
  tags: 
    - common
    - dependencies

- name: Ensure keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes
  tags: 
    - docker
    - setup

- name: Download Docker GPG key
  get_url:
    url: "{{ docker_gpg_key }}"
    dest: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes
  tags: 
    - docker
    - setup
    - keys

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: yes
  tags: 
    - docker
    - setup
    - repository

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  tags: 
    - docker
    - setup

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: no
  become: yes
  tags: 
    - docker
    - install

- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
  tags: 
    - docker
    - service

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
  tags: 
    - docker
    - users
