---
- name: Install dependencies
  apt:
    name: "{{ docker_dependencies }}"
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_key }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
