apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: open4goods
spec:
  storageClassName: manual  # Doit correspondre au PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

