---
- name: Ensure kubm1 points to the correct IP
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '\skubm1$'
    line: "10.0.2.15 kubm1"
    state: present
    backup: yes

- name: Apply Flannel CNI manifest
  ansible.builtin.command:
    cmd: "kubectl apply -f {{ flannel_manifest_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: flannel_apply
  changed_when: flannel_apply.rc == 0
  tags: flannel

- name: Wait for Flannel pods to be Running
  ansible.builtin.shell: >
    kubectl get pods -n {{ flannel_namespace }} -l {{ flannel_label_selector }} -o jsonpath='{.items[*].status.phase}' | grep -v Running || true
  register: flannel_status
  retries: "{{ flannel_wait_retries }}"
  delay: "{{ flannel_wait_delay }}"
  until: flannel_status.stdout == ""
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false
  failed_when: false
  tags: flannel
