---
# === Kubernetes version (dérivée de group_vars/all.yml) ===
k8s_version: "{{ k8s_release | regex_replace('^v','') }}"
# Paquets K8s
k8s_packages:
  - kubeadm
  - kubelet
  - kubectl

# === Containerd (config conseillée pour K8s) ===
containerd_config: |
  version = 2
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "registry.k8s.io/pause:3.10"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
        runtime_type = "io.containerd.runc.v2"
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true


# === Sysctl ===
sysctl_params:
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1
  vm.swappiness: 0

# === Kubeconfig ===
kubeconfig_path: "/etc/kubernetes/admin.conf"
