---
# === Kubernetes version (prends la 1.31.x dispo) ===
k8s_version: "1.31.1"

# Paquets K8s
k8s_packages:
  - kubeadm
  - kubelet
  - kubectl

# === Containerd (config conseillée pour K8s) ===
containerd_config: |
  version = 2
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = "registry.k8s.io/pause:3.9"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
        runtime_type = "io.containerd.runc.v2"
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true

# === Réseau ===
pod_network_cidr: "10.244.0.0/16"
flannel_manifest_url: "https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"
flannel_wait_timeout: "5m"

# === Sysctl ===
sysctl_params:
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1
  vm.swappiness: 0

# === Kubeconfig ===
kubeconfig_path: "/etc/kubernetes/admin.conf"

