---
galaxy_info:
  author: loic
  description: "Installation d’un environnement DevOps (Ansible, fzf, lazygit, etc.)"
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - all
dependencies: []
