- name: Ensure .kube directory exists
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy admin.conf to user kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    remote_src: yes

- name: Deploy local-path-provisioner
  become: yes
  become_user: "{{ ansible_user }}"
  command: >
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Wait for nodes to be Ready
  become: yes
  become_user: "{{ ansible_user }}"
  shell: |
    kubectl wait --for=condition=Ready node --all --timeout=300s
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

