---
# Variables spécifiques si besoin
ansible_venv: "{{ ansible_env.HOME }}/ansible_venv"
requirements_file: "{{ ansible_env.HOME }}/nudger/infra/k8s-ansible/requirements.yml"
user_home: "{{ ansible_env.HOME }}"
bin_dir: "{{ user_home }}/bin"
