---
- name: Add Kubernetes GPG key
  ansible.builtin.get_url:
    url: "{{ kubernetes_gpg_key }}"
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
  become: yes

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "{{ kubernetes_repo }}"
    state: present
    filename: kubernetes
    update_cache: yes
  become: yes

- name: Install Kubernetes packages
  apt:
    name: "{{ kubernetes_packages }}"
    state: present
    update_cache: yes

- name: Hold packages at specific version
  command: apt-mark hold "{{ item }}"
  loop: "{{ kubernetes_packages }}"

- name: Ensure kubelet is running
  service:
    name: kubelet
    state: started
    enabled: yes
