---
- name: Include common vars
  include_vars:
    file: ../../common/vars/main.yml


- name: Install common dependencies
  apt:
    name: "{{ common_dependencies }}"
    state: present
    update_cache: yes
  become: yes

- name: Ensure keyring directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes


- name: Download Kubernetes GPG key (ASCII)
  get_url:
    url: "{{ kubernetes_gpg_key }}"
    dest: /tmp/kubernetes-archive-keyring.asc
    mode: '0644'
  become: yes

- name: Convert GPG key to binary keyring format
  command: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg /tmp/kubernetes-archive-keyring.asc"
  args:
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  become: yes

- name: Remove temporary ASCII GPG key
  file:
    path: /tmp/kubernetes-archive-keyring.asc
    state: absent
  become: yes

- name: Remove old Kubernetes repo file if exists
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent
  become: yes

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "{{ kubernetes_repo }}"
    state: present
    filename: kubernetes
    update_cache: yes
  become: yes

- name: Force APT update
  apt:
    update_cache: yes
  become: yes

- name: Install Kubernetes packages
  apt:
    name: "{{ kubernetes_packages }}"
    state: present
    update_cache: yes
  become: yes

- name: Hold packages at specific version
  command: apt-mark hold "{{ item }}"
  loop: "{{ kubernetes_packages }}"
  become: yes

- name: Ensure kubelet is running
  service:
    name: kubelet
    state: started
    enabled: yes
  become: yes

