---
- name: Pre-create remote tmp for root (quiet the warning)
  become: true
  ansible.builtin.file:
    path: /tmp/.ansible-root
    state: directory
    owner: root
    group: root
    mode: "0700"
