---

- name: Create directory for APT keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: prerequisites

- name: Add Kubernetes GPG key (modern method)
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    mode: '0644'
  tags: prerequisites

- name: Add Kubernetes repository
  apt_repository:
    repo: "{{ k8s_repo }}"
    state: present
    filename: kubernetes
    update_cache: yes
  tags: prerequisites

- name: Install prerequisites and Kubernetes packages
  apt:
    name: "{{ ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'software-properties-common'] + k8s_packages }}"
    state: present
    update_cache: yes
  tags: kubernetes_packages

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ k8s_packages }}"
  tags: kubernetes_packages

- name: Load br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present
  become: yes
  tags: kernel_modules

- name: Ensure br_netfilter module loads on boot
  copy:
    dest: /etc/modules-load.d/br_netfilter.conf
    content: "br_netfilter\n"
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags: kernel_modules

- name: Apply sysctl parameters
  community.general.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ sysctl_params | dict2items }}"
  tags: sysctl

- name: Télécharger containerd 2.6.9
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.7.27/containerd-1.7.27-linux-amd64.tar.gz
    dest: /tmp/containerd-1.7.27-linux-amd64.tar.gz
    mode: '0644'
    timeout: 300
  retries: 3
  delay: 10
  tags: containerd_install

- name: Extraire containerd
  unarchive:
    src: /tmp/containerd-1.7.27-linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/bin/containerd
  tags: containerd_install

- name: Installer le service systemd containerd
  copy:
    dest: /etc/systemd/system/containerd.service
    content: |
      [Unit]
      Description=containerd container runtime
      Documentation=https://containerd.io
      After=network.target local-fs.target
      Wants=network.target

      [Service]
      ExecStart=/usr/local/bin/containerd
      Restart=always
      RestartSec=5
      Delegate=yes
      KillMode=process
      OOMScoreAdjust=-999
      LimitNOFILE=1048576
      LimitNPROC=infinity
      LimitCORE=infinity
      TasksMax=infinity

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
  notify: Restart containerd
  tags: containerd_install

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  tags: containerd_install

- name: Configurer containerd avec template
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: Restart containerd
  tags: containerd_config

- name: Start and enable containerd
  systemd:
    name: containerd
    state: started
    enabled: yes
  tags: containerd_install

- name: Télécharger crictl binaire
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.28.0/crictl-v1.28.0-linux-amd64.tar.gz
    dest: /tmp/crictl.tar.gz
    mode: '0644'
  tags: crictl

- name: Extraire crictl
  unarchive:
    src: /tmp/crictl.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
    creates: /usr/local/bin/crictl
  tags: crictl

- name: Vérifier que CRI répond
  ansible.builtin.command: crictl info
  register: crictl_check
  changed_when: false
  failed_when: crictl_check.rc != 0
  tags: crictl

- name: Initialize Kubernetes cluster (master only)
  ansible.builtin.command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --control-plane-endpoint={{ groups['k8s_masters'][0] }}
    --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  when: inventory_hostname == groups['k8s_masters'][0]
  register: kubeadm_init
  notify:
    - Save kubeconfig file
    - configure kubectl
  tags: kubernetes_init

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    remote_src: yes
  become: yes
