---
- name: Bootstrap Flux (secret + GitRepository + Kustomizations)
  hosts: k8s_masters
  become: true

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: /etc/kubernetes/admin.conf
    kubernetes.core.k8s_info:
      kubeconfig: /etc/kubernetes/admin.conf
    kubernetes.core.helm:
      kubeconfig: /etc/kubernetes/admin.conf
    kubernetes.core.helm_repository:
      kubeconfig: /etc/kubernetes/admin.conf
  collections:
    - kubernetes.core

  vars_files:
    - ../group_vars/vault.yml

  roles:
    - role: flux_bootstrap

