---
- name: Bootstrap Flux (secret + GitRepository + Kustomizations)
  hosts: k8s_masters
  become: true
  collections:
    - kubernetes.core

  vars_files:
    - ../group_vars/vault.yml

  roles:
    - role: flux_bootstrap

