---
- name: Configure Kubernetes Cluster
  hosts: all
  become: yes
  vars_files:
    - roles/common/vars/main.yml
    - roles/docker/vars/main.yml
    - roles/kubernetes/vars/main.yml
    - roles/containerd/vars/main.yml
    - meta/main.yml

  pre_tasks:
    - name: Disable swap (for all nodes)
      import_tasks: disable_swap.yml
      when: inventory_hostname in groups['k8s_masters'] or inventory_hostname in groups['k8s_workers']

  roles:
    - role: docker
      tags: docker
    - role: kubernetes
      tags: kubernetes
    - role: containerd
      tags: containerd
  environment:
    K8S_AUTH_KUBECONFIG: /etc/kubernetes/admin.conf

