---
- name: Configure Kubernetes Cluster
  hosts: all   # ou un groupe 'k8s_all' si tu as masters+workers
  become: true

  # Environment for kubectl/k8s modules (fallback — les rôles mettent déjà KUBECONFIG quand nécessaire)
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  pre_tasks:
    # ---- Swap must be disabled before kubeadm ----
    - name: Disable swap immediately (runtime)
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb | int > 0
      changed_when: false

    - name: Ensure swap is disabled on boot (comment fstab entries)
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^\s*([^#]\S+\s+\S+\s+swap\s+\S+.*)$'
        replace: '# \1'

  roles:
    - role: docker       # installe Docker CE (si tu l’utilises) — sinon supprime ce rôle
      tags: [docker]

    - role: kubernetes   # ajoute repo pkgs.k8s.io + kubeadm/kubelet/kubectl (pinned)
      tags: [kubernetes]

    - role: containerd   # installe containerd + init master + Flannel (auto-namespace)
      tags: [containerd]

