alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias vu='vagrant up'
alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias k='kubectl'
alias kd='kubectl describe'
alias kcc='kubectl config current-context'
alias kg='kubectl get'
alias kga='kubectl get all --all-namespaces'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias ksgp='kubectl get pods -n kube-system'
alias kss='kubectl get services -n kube-system'
alias kuc='kubectl config use-context'
alias vu='vagrant up'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias gitq='git add . && git commit -m "clean" && git push'
alias frec='flux -n flux-system reconcile kustomization cluster-lab --with-source --timeout=2m'
alias reconcil= 'flux -n flux-system reconcile source git gitops'
alias reconcilkustom='flux -n flux-system reconcile kustomization cluster-lab'
