alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias vu='vagrant up'
alias ll='ls -laFh --color=auto'
alias la='ls -A'
alias l='ls -larth'
alias s='sudo -s'
alias k='kubectl'
alias kcc='kubectl config current-context'
alias kg='kubectl get'
alias kga='kubectl get all --all-namespaces'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias ksgp='kubectl get pods -n kube-system'
alias kss='kubectl get services -n kube-system'
alias kuc='kubectl config use-context'
alias vu='vagrant up'

