---
- name: Restart containerd
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true

- name: Restart kubelet
  become: true
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: true

- name: Save kubeconfig file
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: '0600'
