---
# roles/containerd/handlers/main.yml
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
- name: Restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes
  become: yes

- name: Save kubeconfig file
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0600'

- name: Configure kubectl
  become: yes
  command: kubectl config set-context --current --namespace=default

