apiVersion: v1
data:
  config.conf: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: "iptables"
    clusterCIDR: "10.244.0.0/16"
    clientConnection:
      kubeconfig: "/var/lib/kube-proxy/kubeconfig.conf"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.conf":"apiVersion: kubeproxy.config.k8s.io/v1alpha1\nkind: KubeProxyConfiguration\nmode: \"iptables\"\nclusterCIDR: \"10.244.0.0/16\"\nclientConnection:\n  kubeconfig: \"/var/lib/kube-proxy/kubeconfig.conf\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"kube-proxy","namespace":"kube-system"}}
  creationTimestamp: "2025-08-14T03:50:40Z"
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "3160"
  uid: 42dc9398-c80d-4e77-abae-d4ecc5690754
