---
# Kubernetes minor to track; repo URL is built from this.
k8s_version: "1.28.5"
k8s_packages:
  - kubelet
  - kubeadm
  - kubectl

# pkgs.k8s.io uses per-minor repos and a keyring
k8s_repo: >-
  deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg]
  https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/ /

k8s_gpg_key: >-
  https://pkgs.k8s.io/core:/stable:/v{{ k8s_version.split('.')[0:2] | join('.') }}/deb/Release.key

# Containerd sysctls; keep them here for easy override
sysctl_params:
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1
  vm.swappiness: 0

# Networking (Flannel)
pod_network_cidr: "10.244.0.0/16"
flannel_manifest_url: "https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"
# Wait timeout for DaemonSet rollout (e.g., "5m", "180s")
flannel_wait_timeout: "5m"

# Kubeconfig path on master (created by kubeadm init)
kubeconfig_path: "/etc/kubernetes/admin.conf"
