apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: open4goods
    name: data-my-xwiki-mysql-0
