# Default values for node.
# Simplified for MySQL usage.

cluster:
  enabled: false
  replicas: 1

image:
  name: xwiki
  pullPolicy: IfNotPresent
  tag: ''

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  sessionAffinity: ClientIP


resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

javaOpts:
  - "-Xmx1024m"
  - "-Xmx1g"

extraEnvVars:
  - name: DB_HOST
    value: my-xwiki-mysql

workloadStateful: true

securityContext:
  enabled: false
  fsGroup: 101

containerSecurityContext:
  enabled: false
  runAsUser: 100
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"

##
## MySQL chart configuration
##
mysql:
  enabled: true
  auth:
    rootPassword: "xwiki"
    username: "xwiki"
    password: "xwiki"
    database: "xwiki"
  initdbScripts:
    00-init.sql: |
      grant all privileges on *.* to xwiki@'%'
  primary:
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      character-set-server=utf8mb4
      collation-server=utf8mb4_bin
      bind-address=*
      max_allowed_packet=16M
      log-error=/opt/bitnami/mysql/logs/mysqld.log
    persistence:
      enabled: true
      storageClass: ""
      size: "2Gi"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"

ingress:
  enabled: false

istio:
  enabled: false

# Simplified probes
probes:
  startup:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 60
    periodSeconds: 30
    failureThreshold: 5
  liveness:
    enabled: true
    httpGet:
      enabled: true
      path: /rest
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    enabled: true
    httpGet:
      enabled: true
      path: /rest/wikis/xwiki/spaces
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 10

