apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-single-node
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"     # <--- important pour un seul nœud
  fsType: ext4

