# Default values for node.
# Simplified for MySQL usage.

cluster:
  enabled: false
  replicas: 1

image:
  name: xwiki
  pullPolicy: IfNotPresent
  tag: ''

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  sessionAffinity: ClientIP
  externalIPs: []

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

javaOpts:
  - "-Xmx1024m"
  - "-Xmx1g"

extraEnvVars:
  - name: DB_HOST
    value: nudger-xwiki-mysql

workloadStateful: true

securityContext:
  enabled: false
  fsGroup: 101

containerSecurityContext:
  enabled: false
  runAsUser: 100
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"

podDisruptionBudget:
  enabled: false


persistence:
  enabled: true
  size: 5Gi
  storageClass: longhorn   # <== on bascule ici sur Longhorn
  accessModes:
    - ReadWriteOnce
##
## MySQL chart configuration
##
mysql:
  enabled: true
  initdbScripts:
    00-init.sql: |
      grant all privileges on *.* to xwiki@'%'
  primary:
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      character-set-server=utf8mb4
      collation-server=utf8mb4_bin
      bind-address=0.0.0.0
      max_allowed_packet=16M
      log-error=/opt/bitnami/mysql/logs/mysqld.log
    persistence:
      enabled: true
      size: 5Gi
      storageClass: longhorn   # <== on bascule ici sur Longhorn
      accessModes:
        - ReadWriteOnce
    resources:
      requests:
        memory: "1Gi"
        cpu: "400m"
      limits:
        memory: "2Gi"
        cpu: "400m"
    livenessProbe: 
      enabled: false
    startupProbe: 
      enabled: false
    readinessProbe:
      enabled: false
    customLivenessProbe: {}
    customReadinessProbe: {}
    customStartupProbe: {}
ingress:
  enabled: false

istio:
  enabled: false
  gateway:
    enabled: false
  tls:
    certificate:
      enabled: false
# --- Autoscaling ---
autoscaling:
  enabled: false
postgresql:
  enabled: false

mysql:
  enabled: true
mariadb:
  enabled: false
logback:
  enabled: false
glowroot:
  enabled: false
  properties: {}
prometheus:
  enabled: false
  javaagent:
    enabled: false
infinispan:
  enabled: false

customJdbc:
  enabled: false
solr:
  enabled: false
propertiesSecret:
  enabled: false
  name: ""
volumePermissions:
  enabled: false
  containerSecurityContext: {}
initContainers:
  database:
    enabled: false
  extra:
    enabled: false
  solr:
    enabled: false
externalDB:
  enabled: true
  existingSecret: xwiki-mysql-auth
  rootPassword: ""
  user: ""
  password: ""
  database: ""

# Simplified probes for XWiki (HTTP)
probes:
  startup:
    enabled: false
    initialDelaySeconds: 120
    timeoutSeconds: 60
    periodSeconds: 30
    failureThreshold: 5
  liveness:
    enabled: false
    httpGet:
      enabled: true
      path: /rest
    initialDelaySeconds: 30
    timeoutSeconds: 6
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    enabled: false
    httpGet:
      enabled: true
      path: /rest/wikis/xwiki/spaces
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 30
    failureThreshold: 10
