# Default values for node.
# Simplified for MySQL usage.

cluster:
  enabled: false
  replicas: 1

image:
  name: xwiki
  pullPolicy: IfNotPresent
  tag: ''

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  sessionAffinity: ClientIP

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

javaOpts:
  - "-Xmx1024m"
  - "-Xmx1g"

extraEnvVars:
  - name: DB_HOST
    value: my-xwiki-mysql

workloadStateful: true

securityContext:
  enabled: false
  fsGroup: 101

containerSecurityContext:
  enabled: false
  runAsUser: 100
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"

##
## MySQL chart configuration
##
mysql:
  enabled: true
  auth:
    rootPassword: "xwiki"
    username: "xwiki"
    password: "xwiki"
    database: "xwiki"
  initdbScripts:
    00-init.sql: |
      grant all privileges on *.* to xwiki@'%'
  primary:
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      character-set-server=utf8mb4
      collation-server=utf8mb4_bin
      bind-address=*
      max_allowed_packet=16M
      log-error=/opt/bitnami/mysql/logs/mysqld.log
    persistence:
      enabled: true
      storageClass: ""
      size: "2Gi"
      selector:
        matchLabels:
          type: mysql
    resources:
      requests:
        memory: "1Gi"
        cpu: "400m"
      limits:
        memory: "2Gi"
        cpu: "400m"
    startupProbe:
      exec:
        command:
          - /bin/bash
          - -ec
          - |
            password_aux="${MYSQL_ROOT_PASSWORD:-}"
            if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
            fi
            mysqladmin ping --protocol=tcp -h 127.0.0.1 -uroot -p"${password_aux}"
      failureThreshold: 10
      initialDelaySeconds: 150
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    livenessProbe:
      exec:
        command:
          - /bin/bash
          - |
            password_aux="${MYSQL_ROOT_PASSWORD:-}"
            if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
            fi
            mysqladmin ping --protocol=tcp -h 127.0.0.1 -uroot -p"${password_aux}"
      initialDelaySeconds: 80
      periodSeconds: 10
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
          - /bin/bash
          - -ec
          - |
            password_aux="${MYSQL_ROOT_PASSWORD:-}"
            if [[ -f "${MYSQL_ROOT_PASSWORD_FILE:-}" ]]; then
                password_aux=$(cat "$MYSQL_ROOT_PASSWORD_FILE")
            fi
            mysqladmin ping --protocol=tcp -h 127.0.0.1 -uroot -p"${password_aux}"
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 3

ingress:
  enabled: false

istio:
  enabled: false

# Simplified probes for XWiki (HTTP)
probes:
  startup:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 60
    periodSeconds: 30
    failureThreshold: 5
  liveness:
    enabled: true
    httpGet:
      enabled: true
      path: /rest
    initialDelaySeconds: 30
    timeoutSeconds: 6
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    enabled: true
    httpGet:
      enabled: true
      path: /rest/wikis/xwiki/spaces
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 30
    failureThreshold: 10
