apiVersion: v1
kind: PersistentVolume
metadata:
  name: xwiki-pv
  labels:
    type: xwiki
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/xwiki

