---
- name: Configure Kubernetes Cluster
  hosts: all
  become: yes
  vars_files:
    - roles/docker/vars/main.yml
    - roles/kubernetes/vars/main.yml

  pre_tasks:
    - name: Disable swap (for all nodes)
      import_tasks: disable_swap.yml
      when: inventory_hostname in groups['k8s_masters'] or inventory_hostname in groups['k8s_workers']

  roles:
    - role: docker
      tags: docker
    - role: kubernetes
      tags: kubernetes

- name: Additional Master Node Configuration
  hosts: k8s_masters
  become: yes
  tasks:
    - name: Initialize Kubernetes cluster (run only once)
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      when: inventory_hostname == groups['k8s_masters'][0]
      register: kubeadm_init
      notify: save_kubeconfig

  handlers:
    - name: save_kubeconfig
      copy:
        content: "{{ kubeadm_init.stdout }}"
        dest: /etc/kubernetes/admin.conf
