---
# pkgs.k8s.io uses per-minor repos and a keyring

# Added by rename_role_var.sh (from vars/main.yml)
containerd_sysctl_params:
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1
  vm.swappiness: 0

# Added by rename_role_var.sh (from vars/main.yml)
containerd_kubeconfig_path: "/etc/kubernetes/admin.conf"

# Added by rename_role_var.sh (from vars/main.yml)
containerd_kubeconfig_admin_path: "{{ containerd_kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
