---
# Containerd install + config
- name: Remove legacy containerd config if present
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent
  become: true
  tags: [containerd]
- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: true
  become: true
  tags: [containerd]
- name: Ensure /etc/containerd dir exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"
  become: true
  tags: [containerd]
- name: Write crictl.yaml pointing to containerd
  ansible.builtin.copy:
    dest: /etc/crictl.yaml
    mode: "0644"
    content: |
      runtime-endpoint: unix:///var/run/containerd/containerd.sock
      image-endpoint: unix:///var/run/containerd/containerd.sock
      timeout: 10
      debug: false
  become: true
  tags: [containerd]
- name: Deploy containerd config
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    mode: "0644"
    content: "{{ containerd_config }}"
  notify: Restart containerd
  become: true
  tags: [containerd]
- name: Ensure containerd is running and enabled
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
  become: true
  tags: [containerd]
