---
# --- Derive apiserver_host_global if missing ---
- name: Get cluster server URL from admin kubeconfig (only if needed)
  ansible.builtin.shell: |
    set -euo pipefail
    kubectl config view --kubeconfig="{{ containerd_kubeconfig_admin_path }}" --minify \
      -o jsonpath='{.clusters[0].cluster.server}'
  args: { executable: /bin/bash }
  register: _cluster_server_url_from_kubeconfig
  changed_when: false
  when:
    - apiserver_host_global is not defined
    - inventory_hostname == groups['k8s_masters'][0]
  become: true

- name: Derive apiserver_host_global (fallback to node IP)
  ansible.builtin.set_fact:
    apiserver_host_global: >-
      {{
        (
          _cluster_server_url_from_kubeconfig.stdout | default('', true)
          | regex_replace('^https?://', '')
          | regex_replace(':.*$', '')
        )
        | default(ansible_default_ipv4.address, true)
      }}
  when:
    - apiserver_host_global is not defined
    - inventory_hostname == groups['k8s_masters'][0]

# Avant d’appliquer Flannel : wait /readyz sur l’host réel
- name: Wait /readyz on apiserver (from kubeconfig)
  ansible.builtin.shell: |
    set -euo pipefail
    H="{{ apiserver_host_global }}"
    for i in $(seq 1 60); do
      if curl -sf --cacert /etc/kubernetes/pki/ca.crt \
         --cert   /etc/kubernetes/pki/apiserver-kubelet-client.crt \
         --key    /etc/kubernetes/pki/apiserver-kubelet-client.key \
         "https://${H}:6443/readyz" >/dev/null 2>&1; then
        exit 0
      fi
      sleep 2
    done
    exit 1
  args: { executable: /bin/bash }
  changed_when: false
  become: true
  when: inventory_hostname == groups['k8s_masters'][0]
- name: Wait for kube-apiserver container to be running
  shell: |
    set -euo pipefail
    for i in $(seq 1 60); do
      if crictl ps --name kube-apiserver | grep -q Running; then exit 0; fi
      sleep 2
    done
    echo "kube-apiserver not running"; exit 1
  args: { executable: /bin/bash }

- name: Debug bundle for control-plane failure
  shell: |
    echo "=== kubelet ==="; systemctl status --no-pager kubelet || true
    echo "=== kubelet logs ==="; journalctl -u kubelet -n 300 --no-pager || true
    echo "=== apiserver container ==="; crictl ps -a | grep kube-apiserver || true
    APISRV_ID=$(crictl ps -a --name kube-apiserver -q | head -n1); [ -n "$APISRV_ID" ] && crictl logs "$APISRV_ID" | tail -n 300 || true
    echo "=== apiserver manifest ==="; sed -n '1,200p' /etc/kubernetes/manifests/kube-apiserver.yaml || true
    echo "=== etcd ==="; crictl ps -a | grep etcd || true
    ETCD_ID=$(crictl ps -a --name etcd -q | head -n1); [ -n "$ETCD_ID" ] && crictl logs "$ETCD_ID" | tail -n 200 || true

- name: Ensure kube-apiserver is listening on 6443 right now
  ansible.builtin.shell: ss -ltn | awk '{print $4}' | grep -qE '(^|:|])6443$'
  args: { executable: /bin/bash }
  register: apisock
  changed_when: false
  retries: 20
  delay: 2
  until: apisock.rc == 0
  become: true
  when: inventory_hostname == groups['k8s_masters'][0]
- name: Render kube-flannel namespace YAML
  ansible.builtin.command:
    argv: ["kubectl","create","ns","kube-flannel","--dry-run=client","-o","yaml"]
  environment: { KUBECONFIG: "{{ containerd_kubeconfig_admin_path }}" }
  register: ns_yaml
  changed_when: false
  when: inventory_hostname == groups['k8s_masters'][0]

- name: Apply kube-flannel namespace (idempotent)
  ansible.builtin.command:
    argv: ["kubectl","apply","-f","-"]
  args:
    stdin: "{{ ns_yaml.stdout }}"
  environment: { KUBECONFIG: "{{ containerd_kubeconfig_admin_path }}" }
  register: ns_apply
  changed_when: "'created' in ns_apply.stdout or 'configured' in ns_apply.stdout"
  when: inventory_hostname == groups['k8s_masters'][0]

# Flannel CNI install (after kubeadm init)
- name: Apply Flannel CNI (use kubeconfig server, retries + readyz)
  ansible.builtin.shell: |
    set -euo pipefail
    S="$(kubectl config view --kubeconfig="{{ containerd_kubeconfig_admin_path }}" --minify -o jsonpath='{.clusters[0].cluster.server}')"
    H="$(printf '%s' "$S" | sed -E 's#^https?://##; s#:.*$##')"

    for i in $(seq 1 10); do
      if curl -sf --cacert /etc/kubernetes/pki/ca.crt \
         --cert   /etc/kubernetes/pki/apiserver-kubelet-client.crt \
         --key    /etc/kubernetes/pki/apiserver-kubelet-client.key \
         "https://${H}:6443/readyz" >/dev/null 2>&1; then
        if kubectl --kubeconfig "{{ containerd_kubeconfig_admin_path }}" \
                   apply --validate=false \
                   -f "{{ flannel_manifest_url }}"; then
          exit 0
        fi
      fi
      sleep 3
    done
    exit 1
  args: { executable: /bin/bash }
  register: flannel_apply
  changed_when: "'created' in flannel_apply.stdout or 'configured' in flannel_apply.stdout"
  become: true
  when: inventory_hostname == groups['k8s_masters'][0]

- name: Wait for Flannel DaemonSet to be ready
  ansible.builtin.command: >
    kubectl -n kube-flannel rollout status ds/kube-flannel-ds --timeout={{ flannel_wait_timeout }}
            --server https://{{ apiserver_host_global }}:6443 \
            --insecure-skip-tls-verify
            --kubeconfig {{ containerd_kubeconfig_admin_path }}
  register: flannel_rollout
  changed_when: false
  retries: 3
  delay: 20
  until: flannel_rollout.rc == 0
  become: true
  when: inventory_hostname == groups['k8s_masters'][0]

- name: Ensure flannel has --ip-masq=true
  ansible.builtin.shell: |
    set -euo pipefail
    if ! kubectl -n kube-flannel get ds kube-flannel-ds -o json \
      | jq -e '.spec.template.spec.containers[0].args[]? | select(. == "--ip-masq=true")' >/dev/null; then
      kubectl -n kube-flannel patch ds kube-flannel-ds --type='json' -p='[
        {"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--ip-masq=true"}
      ]'
    fi
  args: { executable: /bin/bash }
  register: flannel_ipmasq_patch
  changed_when: flannel_ipmasq_patch.rc == 0

- name: Rollout kube-flannel after ip-masq change
  ansible.builtin.command: kubectl -n kube-flannel rollout status ds/kube-flannel-ds --timeout={{ flannel_wait_timeout }}
  when: flannel_ipmasq_patch is changed
