---
# ----------------------------
# Kubernetes repo & packages (FORCE v1.31)
# ----------------------------
- name: Ensure deps for HTTPS APT
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true
  become: true
  tags: [k8s]
- name: Purge any previous Kubernetes sources
  ansible.builtin.shell: |
    rm -f /etc/apt/sources.list.d/kubernetes.list
    sed -i '/pkgs\\.k8s\\.io\\/core:\\/stable:\\//d' /etc/apt/sources.list || true
  args: { executable: /bin/bash }
  changed_when: true
  become: true
  tags: [k8s]
- name: Remove legacy keyring if present
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: absent
  become: true
  tags: [k8s]
- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true
  tags: [k8s]
- name: Fetch Kubernetes Release.key ({{ k8s_minor }})
  ansible.builtin.get_url:
    url: "{{ k8s_gpg_key }}"
    dest: /etc/apt/keyrings/kubernetes-Release.key
    mode: "0644"

- name: Dearmor -> kubernetes-archive-keyring.gpg
  ansible.builtin.command:
    cmd: "gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg /etc/apt/keyrings/kubernetes-Release.key"
  args:
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  become: true
  tags: [k8s]
- name: Ensure keyring perms
  ansible.builtin.file:
    path: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: file
    mode: "0644"
  become: true
  tags: [k8s]
- name: Write kubernetes.list (pin to {{ k8s_minor }})
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    mode: "0644"
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] {{ k8s_repo }} /
  become: true
  tags: [k8s]
- name: Apt-get update (force refresh)
  ansible.builtin.shell: |
    rm -rf /var/lib/apt/lists/*
    apt-get update
  args: { executable: /bin/bash }
  changed_when: false
  become: true
  tags: [k8s]
- name: Unhold kube packages if held
  ansible.builtin.shell: |
    set -e
    for p in kubeadm kubelet kubectl; do
      if apt-mark showhold | grep -q "^$p$"; then apt-mark unhold "$p"; fi
    done
  args: { executable: /bin/bash }
  changed_when: false
  become: true
  tags: [k8s]
- name: Install/upgrade Kubernetes tools to latest in v1.31 repo
  ansible.builtin.apt:
    name: "{{ k8s_packages }}"
    state: latest
    update_cache: true
  become: true
  tags: [k8s]
- name: Enable & restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: restarted
  become: true
  tags: [k8s]
