---
# ----------------------------
# Kubeconfig pour l'user ansible
# ----------------------------
- name: Ensure .kube directory exists for ansible user
  ansible.builtin.file:
    path: "/home/{{ ansible_user | default('ansible') }}/.kube"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user | default('ansible') }}"
    group: "{{ ansible_user | default('ansible') }}"
  become: true
  when: inventory_hostname == groups['k8s_masters'][0]
- name: Copy admin.conf to ansible user's kubeconfig
  ansible.builtin.copy:
    src: "{{ containerd_kubeconfig_admin_path }}"
    dest: "{{ kubeconfig_user_path }}"
    owner: "{{ ansible_user | default('ansible') }}"
    group: "{{ ansible_user | default('ansible') }}"
    mode: "0600"
    remote_src: true
  become: true
  when: inventory_hostname == groups['k8s_masters'][0]
- name: Ensure KUBECONFIG line in ansible user's .bashrc (for interactive
    shells)
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user | default('ansible') }}/.bashrc"
    line: "export KUBECONFIG=$HOME/.kube/config"
    create: true
    state: present
  become: true
  when: inventory_hostname == groups['k8s_masters'][0]
